import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdad9',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#400009',
        'secondary-container': '#f8dac8',
        'tertiary-container': '#fb8b8d',
        'surface-container-high': '#e4eae4',
        'on-tertiary-fixed-variant': '#7e2a2f',
        'inverse-surface': '#2c322e',
        'coffee-bean': '#2a1e16',
        'on-primary-container': '#004a31',
        error: '#ba1a1a',
        'surface-dim': '#d6dbd6',
        'on-secondary-container': '#755e50',
        'on-primary-fixed': '#002114',
        'paper-white': '#ffffff',
        'surface-bright': '#f5fbf5',
        background: '#f5fbf5',
        primary: '#006c4a',
        surface: '#f5fbf5',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb3b3',
        'on-tertiary-container': '#742328',
        'inverse-primary': '#6fdbaa',
        'error-container': '#ffdad6',
        'on-background': '#171d19',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#dec1af',
        'surface-tint': '#006c4a',
        'on-secondary-fixed': '#28180d',
        'on-secondary-fixed-variant': '#574335',
        'outline-variant': '#bdcac0',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#171d19',
        outline: '#6e7a72',
        'primary-fixed': '#8bf7c4',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#6fdbaa',
        'on-primary-fixed-variant': '#005237',
        'surface-variant': '#dee4de',
        'surface-container-highest': '#dee4de',
        'inverse-on-surface': '#edf2ec',
        'on-surface-variant': '#3e4942',
        'secondary-fixed': '#fbddca',
        'surface-container': '#eaefe9',
        'surface-container-low': '#f0f5ef',
        'primary-container': '#52bf90',
        'heritage-cream': '#fdfcf8',
        'on-error': '#ffffff',
        'garden-leaf-dark': '#3e8f6c',
        secondary: '#705a4c',
        tertiary: '#9c4145',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        base: '8px',
        'margin-desktop': '64px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['Manrope'],
        caption: ['Manrope'],
        'headline-lg': ['Libre Caslon Text'],
        'headline-lg-mobile': ['Libre Caslon Text'],
        'body-md': ['Manrope'],
        'headline-md': ['Libre Caslon Text'],
        'display-lg': ['Libre Caslon Text'],
        'label-md': ['Manrope'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config